package be.unamur.info.mdl.service.impl;

import org.springframework.beans.factory.annotation.Autowired;

import be.unamur.info.mdl.dal.entity.User;
import be.unamur.info.mdl.dal.repository.UserRepository;
import be.unamur.info.mdl.service.UserService;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * This class is responsible of all possible services related to the /api/user
 *
 */
@Service("userService")
@Transactional
class UserServiceImpl implements UserService {

  private UserRepository userRepository;


  @Autowired // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  public UserServiceImpl(UserRepository userRepository) {
    this.userRepository = userRepository;
  }

  @Override
  public boolean addUser(User newUser, String rawPassword) {
    // TODO
    userRepository.save(newUser);
    return true;
  }
}