;
CREATE USER IF NOT EXISTS SA SALT '19a5863331d58bf9' HASH 'ba551b74628f1846b0e06cf5b93eb9e191db3c0bfc353057cc4d84d519a437e6' ADMIN;
CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1000;
CREATE TABLE ARTICLE(
    ID BIGINT NOT NULL,
    ABSTRACT, CLOB NOT NULL,
    CREATED_AT DATE,
    JOURNAL VARCHAR(255) NOT NULL,
    JOURNAL_NUMBER VARCHAR(255),
    JOURNAL_VOLUME VARCHAR(255),
    NB_CITATIONS INTEGER,
    NB_VIEWS INTEGER,
    PAGES VARCHAR(255),
    PRICE FLOAT,
    PUBLICATION_MONTH VARCHAR(255),
    PUBLICATION_YEAR INTEGER NOT NULL,
    PUBLISHER VARCHAR(255),
    REFERENCE VARCHAR(255) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    URL VARCHAR(255) NOT NULL,
    CATEGORY_ID BIGINT NOT NULL,
    CREATOR_USER_ID BIGINT NOT NULL
);
ALTER TABLE ARTICLE ADD CONSTRAINT CONSTRAINT_F PRIMARY KEY(ID);
-- 7 +/- SELECT COUNT(*) FROM ARTICLE;
CREATE TABLE ARTICLE_AUTHORS(
    AUTHOR_ID BIGINT NOT NULL,
    ARTICLE_ID BIGINT NOT NULL
);
ALTER TABLE ARTICLE_AUTHORS ADD CONSTRAINT CONSTRAINT_A PRIMARY KEY(AUTHOR_ID, ARTICLE_ID);


CREATE TABLE ARTICLE_IN_STATE(
    STATE_OF_THE_ART_ID BIGINT NOT NULL,
    ARTICLE_ID BIGINT NOT NULL
);
ALTER TABLE ARTICLE_IN_STATE ADD CONSTRAINT CONSTRAINT_A7 PRIMARY KEY(STATE_OF_THE_ART_ID, ARTICLE_ID);
-- 0 +/- SELECT COUNT(*) FROM ARTICLE_IN_STATE;
CREATE TABLE ARTICLE_KEYWORDS(
    ARTICLE_ID BIGINT NOT NULL,
    TAG_ID BIGINT NOT NULL
);
ALTER TABLE ARTICLE_KEYWORDS ADD CONSTRAINT CONSTRAINT_9 PRIMARY KEY(ARTICLE_ID, TAG_ID);
-- 26 +/- SELECT COUNT(*) FROM ARTICLE_KEYWORDS;

CREATE TABLE ARTICLE_REFERENCES(
    ARTICLE_ID BIGINT NOT NULL,
    REFERENCE_ID BIGINT NOT NULL
);
ALTER TABLE ARTICLE_REFERENCES ADD CONSTRAINT CONSTRAINT_1 PRIMARY KEY(ARTICLE_ID, REFERENCE_ID);
-- 0 +/- SELECT COUNT(*) FROM ARTICLE_REFERENCES;
CREATE TABLE AUTHOR(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    SLUG VARCHAR(255) NOT NULL
);
ALTER TABLE AUTHOR ADD CONSTRAINT CONSTRAINT_7 PRIMARY KEY(ID);
-- 24 +/- SELECT COUNT(*) FROM AUTHOR;


CREATE TABLE BOOKMARK(
    ID BIGINT NOT NULL,
    CREATED_AT DATE,
    NAME VARCHAR(255),
    USER_ID BIGINT NOT NULL
);
ALTER TABLE BOOKMARK ADD CONSTRAINT CONSTRAINT_A6 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM BOOKMARK;
CREATE TABLE BOOKMARK_ARTICLE(
    BOOKMARK_ID BIGINT NOT NULL,
    ARTICLE_ID BIGINT NOT NULL
);
ALTER TABLE BOOKMARK_ARTICLE ADD CONSTRAINT CONSTRAINT_C PRIMARY KEY(BOOKMARK_ID, ARTICLE_ID);
-- 0 +/- SELECT COUNT(*) FROM BOOKMARK_ARTICLE;
CREATE TABLE DOMAIN(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL
);
ALTER TABLE DOMAIN ADD CONSTRAINT CONSTRAINT_78 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM DOMAIN;
CREATE TABLE FOLLOWER_TAGS(
    FOLLOWER_ID BIGINT NOT NULL,
    TAG_ID BIGINT NOT NULL
);
ALTER TABLE FOLLOWER_TAGS ADD CONSTRAINT CONSTRAINT_3 PRIMARY KEY(FOLLOWER_ID, TAG_ID);
-- 0 +/- SELECT COUNT(*) FROM FOLLOWER_TAGS;
CREATE TABLE RESEARCH_GROUP(
    ID BIGINT NOT NULL,
    CREATED_AT DATE,
    NAME VARCHAR(255) NOT NULL,
    NOMBRE INTEGER CHECK (NOMBRE >= 1)
);
ALTER TABLE RESEARCH_GROUP ADD CONSTRAINT CONSTRAINT_7E PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM RESEARCH_GROUP;
CREATE TABLE STATE_OF_THE_ART(
    ID BIGINT NOT NULL,
    CREATED_AT DATE,
    DATE DATE NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    SUBJECT VARCHAR(255) NOT NULL,
    USER_ID BIGINT
);
ALTER TABLE STATE_OF_THE_ART ADD CONSTRAINT CONSTRAINT_E PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM STATE_OF_THE_ART;
CREATE TABLE TAG(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    SLUG VARCHAR(255) NOT NULL
);
ALTER TABLE TAG ADD CONSTRAINT CONSTRAINT_14 PRIMARY KEY(ID);
-- 27 +/- SELECT COUNT(*) FROM TAG;

CREATE TABLE TAG_STATES_OF_THEART(
    STATE_OF_THE_ART_ID BIGINT NOT NULL,
    TAG_ID BIGINT NOT NULL
);
ALTER TABLE TAG_STATES_OF_THEART ADD CONSTRAINT CONSTRAINT_4 PRIMARY KEY(STATE_OF_THE_ART_ID, TAG_ID);
-- 0 +/- SELECT COUNT(*) FROM TAG_STATES_OF_THEART;
CREATE TABLE UNIVERSITY(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL
);
ALTER TABLE UNIVERSITY ADD CONSTRAINT CONSTRAINT_2 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM UNIVERSITY;
CREATE TABLE UNIVERSITY_CURRENT(
    UNIVERSITY_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    CURRENT BOOLEAN
);
ALTER TABLE UNIVERSITY_CURRENT ADD CONSTRAINT CONSTRAINT_43 PRIMARY KEY(UNIVERSITY_ID, USER_ID);
-- 0 +/- SELECT COUNT(*) FROM UNIVERSITY_CURRENT;
CREATE TABLE USER(
    ID BIGINT NOT NULL,
    CREATED_AT DATE,
    EMAIL VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    PASSWORD VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PROFIL_ID BIGINT
);
ALTER TABLE USER ADD CONSTRAINT CONSTRAINT_27 PRIMARY KEY(ID);
-- 2 +/- SELECT COUNT(*) FROM USER;

CREATE TABLE USER_FOLLOWER(
    USER_ID BIGINT NOT NULL,
    FOLLOWING_ID BIGINT NOT NULL
);
ALTER TABLE USER_FOLLOWER ADD CONSTRAINT CONSTRAINT_5 PRIMARY KEY(USER_ID, FOLLOWING_ID);
-- 0 +/- SELECT COUNT(*) FROM USER_FOLLOWER;
CREATE TABLE USER_GROUP(
    USER_ID BIGINT NOT NULL,
    GROUP_ID BIGINT NOT NULL
);
ALTER TABLE USER_GROUP ADD CONSTRAINT CONSTRAINT_C6 PRIMARY KEY(USER_ID, GROUP_ID);
-- 0 +/- SELECT COUNT(*) FROM USER_GROUP;
CREATE TABLE USER_PROFIL(
    ID BIGINT NOT NULL,
    DESCRIPTION VARCHAR(255),
    STATUS VARCHAR(255),
    USER_ID BIGINT
);
ALTER TABLE USER_PROFIL ADD CONSTRAINT CONSTRAINT_EE PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM USER_PROFIL;
ALTER TABLE TAG ADD CONSTRAINT UK_1WDPSED5KNA2Y38HNBGRNHI5B UNIQUE(NAME);
ALTER TABLE ARTICLE ADD CONSTRAINT UK_LA4E9L2G2OTN85R9IH4BTNMI UNIQUE(URL);
ALTER TABLE RESEARCH_GROUP ADD CONSTRAINT UK_TQNW4F009P2YD3LLM7TWCAKJ8 UNIQUE(NAME);
ALTER TABLE TAG ADD CONSTRAINT UK_1AFK1Y1O95L8OXXJXSQVELM3O UNIQUE(SLUG);
ALTER TABLE ARTICLE ADD CONSTRAINT UK_RTI6XU203K7HFOHPU89214W6C UNIQUE(REFERENCE);
ALTER TABLE DOMAIN ADD CONSTRAINT UK_GA2SQP4LBOBLQV6OKS9ORYD9Q UNIQUE(NAME);
ALTER TABLE UNIVERSITY ADD CONSTRAINT UK_RU212K5VIB3YVU360FUY3H1G5 UNIQUE(NAME);
ALTER TABLE ARTICLE ADD CONSTRAINT UK_571GX7OQO5XPMGOCEGAIDLCU9 UNIQUE(TITLE);
ALTER TABLE USER ADD CONSTRAINT UK_SB8BBOUER5WAK8VYIIY4PF2BX UNIQUE(USERNAME);
ALTER TABLE AUTHOR ADD CONSTRAINT UK_OR6K6JMYWERXBME223C988BMG UNIQUE(NAME);
ALTER TABLE BOOKMARK ADD CONSTRAINT UK_QG861JFEHKC890J3YENMK1X8L UNIQUE(USER_ID);
ALTER TABLE STATE_OF_THE_ART ADD CONSTRAINT UK_IR1EP0B10CJ4M5ARDGYIMDQGX UNIQUE(NAME);
ALTER TABLE USER ADD CONSTRAINT UK_9V6E6KC6G2AN7GD5QC02GQ6YO UNIQUE(PROFIL_ID);
ALTER TABLE STATE_OF_THE_ART ADD CONSTRAINT UK_RUN71EGQO3FA6795HRUKSKJYK UNIQUE(USER_ID);
ALTER TABLE BOOKMARK ADD CONSTRAINT FK3OGDXSXA4TX6VNDYVPK1FK1AM FOREIGN KEY(USER_ID) REFERENCES USER(ID) NOCHECK;
ALTER TABLE ARTICLE ADD CONSTRAINT FK93OG73GBTF4GU5BG9LNC0RFKO FOREIGN KEY(CREATOR_USER_ID) REFERENCES USER(ID) NOCHECK;
ALTER TABLE USER ADD CONSTRAINT FKIF0O9AXOT4QWP3HQLVGEJ94RU FOREIGN KEY(PROFIL_ID) REFERENCES USER_PROFIL(ID) NOCHECK;
ALTER TABLE ARTICLE_REFERENCES ADD CONSTRAINT FKQ84XVM8KWU6X3BS310XPOKL5P FOREIGN KEY(ARTICLE_ID) REFERENCES ARTICLE(ID) NOCHECK;
ALTER TABLE USER_FOLLOWER ADD CONSTRAINT FK7LYUFBUI36W4JUL3ML7P4K5AR FOREIGN KEY(USER_ID) REFERENCES USER(ID) NOCHECK;
ALTER TABLE FOLLOWER_TAGS ADD CONSTRAINT FKJOEX3ARXL68MM3HGOQ7V6D0EA FOREIGN KEY(TAG_ID) REFERENCES TAG(ID) NOCHECK;
ALTER TABLE ARTICLE ADD CONSTRAINT FKR1RVPEFQ856PKU6RY42T8AS6U FOREIGN KEY(CATEGORY_ID) REFERENCES TAG(ID) NOCHECK;
ALTER TABLE TAG_STATES_OF_THEART ADD CONSTRAINT FKRF27JMQHIUFE316OXHTVS0XNP FOREIGN KEY(STATE_OF_THE_ART_ID) REFERENCES STATE_OF_THE_ART(ID) NOCHECK;
ALTER TABLE ARTICLE_AUTHORS ADD CONSTRAINT FK33EBMLEPMLUHTMDCXCQVTR103 FOREIGN KEY(AUTHOR_ID) REFERENCES ARTICLE(ID) NOCHECK;
ALTER TABLE USER_GROUP ADD CONSTRAINT FKSBEB7HERS5B9RNVCCLMNVOT5N FOREIGN KEY(GROUP_ID) REFERENCES RESEARCH_GROUP(ID) NOCHECK;
ALTER TABLE BOOKMARK_ARTICLE ADD CONSTRAINT FKSW09R2CHNIBIDV5QRXOTTXOOJ FOREIGN KEY(BOOKMARK_ID) REFERENCES BOOKMARK(ID) NOCHECK;
ALTER TABLE FOLLOWER_TAGS ADD CONSTRAINT FKB2NVFI2ATB8HHHCX3CMQH86CX FOREIGN KEY(FOLLOWER_ID) REFERENCES USER(ID) NOCHECK;
ALTER TABLE USER_FOLLOWER ADD CONSTRAINT FK23901XECCK2PGEWTESGJP6P73 FOREIGN KEY(FOLLOWING_ID) REFERENCES USER(ID) NOCHECK;
ALTER TABLE ARTICLE_KEYWORDS ADD CONSTRAINT FKIDMGMYOLURSCRSOS0ESE1MU8P FOREIGN KEY(TAG_ID) REFERENCES TAG(ID) NOCHECK;
ALTER TABLE ARTICLE_KEYWORDS ADD CONSTRAINT FKIMDOMUAH3TA4HMEB77E68M0WL FOREIGN KEY(ARTICLE_ID) REFERENCES ARTICLE(ID) NOCHECK;
ALTER TABLE ARTICLE_REFERENCES ADD CONSTRAINT FK8EAWEWN44YVIVQ0Y13NAA7R3R FOREIGN KEY(REFERENCE_ID) REFERENCES ARTICLE(ID) NOCHECK;
ALTER TABLE UNIVERSITY_CURRENT ADD CONSTRAINT FKHC7OL0YAVH5D7IWKI8975QCMY FOREIGN KEY(USER_ID) REFERENCES USER(ID) NOCHECK;
ALTER TABLE ARTICLE_AUTHORS ADD CONSTRAINT FK2N7F44D637JPR8I8AK6H6IEEC FOREIGN KEY(ARTICLE_ID) REFERENCES AUTHOR(ID) NOCHECK;
ALTER TABLE ARTICLE_IN_STATE ADD CONSTRAINT FK7BNTAQJ2FVKJI3NCLDND4CW4S FOREIGN KEY(STATE_OF_THE_ART_ID) REFERENCES STATE_OF_THE_ART(ID) NOCHECK;
ALTER TABLE ARTICLE_IN_STATE ADD CONSTRAINT FKCRBJVMODBQVQEMHHIUGN15T1X FOREIGN KEY(ARTICLE_ID) REFERENCES ARTICLE(ID) NOCHECK;
ALTER TABLE TAG_STATES_OF_THEART ADD CONSTRAINT FKG2ERB1QHXRDMK7O4YMN663NBV FOREIGN KEY(TAG_ID) REFERENCES TAG(ID) NOCHECK;
ALTER TABLE USER_PROFIL ADD CONSTRAINT FKANMBAB87G3G6B3N155W3K4E0V FOREIGN KEY(USER_ID) REFERENCES USER(ID) NOCHECK;
ALTER TABLE STATE_OF_THE_ART ADD CONSTRAINT FKPLWR874KK4RXI3CNQN6PEIA4F FOREIGN KEY(USER_ID) REFERENCES USER(ID) NOCHECK;
ALTER TABLE BOOKMARK_ARTICLE ADD CONSTRAINT FKD7PV9AMC1YK0FDQBNHFYL8FTJ FOREIGN KEY(ARTICLE_ID) REFERENCES ARTICLE(ID) NOCHECK;
ALTER TABLE UNIVERSITY_CURRENT ADD CONSTRAINT FKHQ70GENSTSFBK2O3OYPG7GYKE FOREIGN KEY(UNIVERSITY_ID) REFERENCES UNIVERSITY(ID) NOCHECK;
ALTER TABLE USER_GROUP ADD CONSTRAINT FK1C1DSW3Q36679VAIQWVTV36A6 FOREIGN KEY(USER_ID) REFERENCES USER(ID) NOCHECK;
